### ISSUE TITLE
app build crash with production env [3.1.2]

### ISSUE THREAD

**Issue by chrmod** [aexmachina/ember-notify#43]
Running `ember build --environment=production` makes the build crash:
```
version: 0.1.12
Build failed.
Unexpected token punc «(», expected punc «:»
Error
    at new JS_Parse_Error (/home/chrmod/Projects/rebased/finalcloud-dashboard/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/node_modules/uglify-js/lib/parse.js:196:18)
    at js_error (/home/chrmod/Projects/rebased/finalcloud-dashboard/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/node_modules/uglify-js/lib/parse.js:204:11)
    at croak (/home/chrmod/Projects/rebased/finalcloud-dashboard/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/node_modules/uglify-js/lib/parse.js:674:9)
    at token_error (/home/chrmod/Projects/rebased/finalcloud-dashboard/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/node_modules/uglify-js/lib/parse.js:682:9)
    at expect_token (/home/chrmod/Projects/rebased/finalcloud-dashboard/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/node_modules/uglify-js/lib/parse.js:695:9)
    at expect (/home/chrmod/Projects/rebased/finalcloud-dashboard/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/node_modules/uglify-js/lib/parse.js:698:36)
    at /home/chrmod/Projects/rebased/finalcloud-dashboard/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/node_modules/uglify-js/lib/parse.js:1251:13
    at /home/chrmod/Projects/rebased/finalcloud-dashboard/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/node_modules/uglify-js/lib/parse.js:721:24
    at expr_atom (/home/chrmod/Projects/rebased/finalcloud-dashboard/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/node_modules/uglify-js/lib/parse.js:1181:35)
    at maybe_unary (/home/chrmod/Projects/rebased/finalcloud-dashboard/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/node_modules/uglify-js/lib/parse.js:1357:19)
```
it is working properly with **3.1.1**.

Crash is caused by those lines:
* https://github.com/aexmachina/ember-notify/commit/b7c18e26bc1d64cba5228534f1215c6487cf0108#diff-6730b55ac91537d06ddac49f73f066f9R29
* https://github.com/aexmachina/ember-notify/commit/b7c18e26bc1d64cba5228534f1215c6487cf0108#diff-6730b55ac91537d06ddac49f73f066f9R32
* https://github.com/aexmachina/ember-notify/commit/b7c18e26bc1d64cba5228534f1215c6487cf0108#diff-7562eb8eba3c3d86a671045f8c70107eR100

So something is wrong with ES6 transpiling.

**Comment by topaxi** [comment]
It seems to crash due to this line: https://github.com/aexmachina/ember-notify/commit/b7c18e26bc1d64cba5228534f1215c6487cf0108#diff-6730b55ac91537d06ddac49f73f066f9R29

Looks like addons aren't transpiled before minification? Not sure... might be an ember-cli issue.

**Comment by aexmachina** [comment]
Weird, okay I've pushed v3.1.4 which removes these.

**Comment by knownasilya** [comment]
Should be fixed in https://github.com/ember-cli/ember-cli/pull/3564
